network/urls.py
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


from . import views
from .views import index, login_view, logout_view, register, profile, post_view
from .views import  followme, following_view, editpost_view,likes_view,unlikes_view
app_name = 'network'
urlpatterns = [
    path("", views.index, name="index"),
    path("login", views.login_view, name="login"),
    path("logout", views.logout_view, name="logout"),
    path("register", views.register, name="register"),

    path("profile/<str:username>",views.profile, name="profile"),
    path("followme", views.followme, name="followme"),
    path("following", views.following_view, name="following"),
    path("post/<str:username>",views.post_view, name="post"),
    path("editpost",views.editpost_view, name="editpost"),
    path("liked",views.likes_view, name="likes"),
    path("unliked",views.unlikes_view, name="unlikes"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project4/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("network.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

network/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models, connection
from django import forms
from django.http import HttpResponseBadRequest, HttpResponseRedirect, Http404
from django.shortcuts import render
from django.urls import reverse

from PIL import Image
from PIL.Image import core as _imaging

from django.conf import settings
from django.conf.urls.static import static


class User(AbstractUser):
    pass

class Profile(models.Model):
    User = models.ForeignKey('User', on_delete = models.CASCADE)
    Follower = models.ManyToManyField('User', blank=True, related_name="Followers")  #seguidores
    Following = models.ManyToManyField('User',blank=True, related_name= "Following")  #seguindo
    Avatar = models.ImageField(upload_to="media", blank=True)

    @property
    def TotalFollowers(self):
        return self.Followers.all().count()

    @property
    def TotalFollowing(self):
        return self.Following.all().count()


    def __str__(self):
        return f"({self.User})({self.Follower})({self.Following})({self.Avatar})"

class Posts(models.Model):
    User = models.ForeignKey('User', on_delete = models.CASCADE)
    Post = models.TextField(max_length=255)
    Date = models.DateTimeField(auto_now_add=True)
    Likes = models.IntegerField(blank=True, null=True)
    Unlikes = models.IntegerField(blank=True, null=True)

    @property
    def TotalPosts(self):
        return self.Post.all().count()
    @property
    def TotalLikes(self):
        return self.Likes.all().count()
    @property
    def TotalUnLikes(self):
        return self.Unlikes.all().count()

    def __str__(self):
        return f"({self.User})({self.Post})({self.Date}) ({self.Likes}) ({self.Unlikes}) "

class PostsLikes(models.Model):
    User = models.ForeignKey('User', on_delete = models.CASCADE)
    Posts = models.ForeignKey('Posts', on_delete = models.CASCADE )
    Likes = models.BooleanField(default=False)
    Unlikes = models.BooleanField(default=False)

    @property
    def TotalLikes(self):
        return self.Likes.all().count()

    def __str__(self):
        return f"({self.User})({self.Posts})({self.Likes}) ({self.Unlikes})"

network/views.py
import sqlite3, datetime, os, os.path, time, json, re, requests

from django import forms
from django.contrib import admin
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist
from django.core.paginator import Paginator
from django.db import IntegrityError,connection, models
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseNotFound, JsonResponse
from django.shortcuts import render
from django.urls import reverse,include, path
from django.views.decorators.csrf import csrf_exempt


from . import views
from .models import User, Profile, Posts, PostsLikes


class NewPostForm(forms.Form):
    NewPost = forms.CharField(label= "What are you thinking?",widget=forms.Textarea( attrs={'rows':'3' , 'cols':'140','text-align': 'center' }))


def index(request):
    if request.user.is_authenticated:
        result_list = []
        result_list = allposts()
        paginator = Paginator(result_list, 10)
        #print(paginator.count , paginator.num_pages )

        page_number = request.GET.get('page')
        page_itens = paginator.get_page(page_number)
        #print("ALL POSTS PAGE")
        #print(page_itens)

        context={
            "NewPostForm":NewPostForm(),
            "page_obj": page_itens,
            "UserEdit" : request.user.username,
        }
        return render(request, "network/index.html", context)



    else:
        context={
            "Message": "Please Login or join our Network",
        }
        return render(request, "network/login.html", context)






def login_view(request):
    if request.method == "POST":

        # Attempt to sign user in
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        # Check if authentication successful
        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse("network:index"))
        else:
            return render(request, "network/login.html", {
                "Message": "Invalid username and/or password."
            })
    else:
        return render(request, "network/login.html")


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse("network:index"))


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        email = request.POST["email"]
        # Ensure password matches confirmation
        password = request.POST["password"]
        confirmation = request.POST["confirmation"]
        if password != confirmation:
            return render(request, "network/register.html", {
                "Message": "Passwords must match."
            })
        # Attempt to create new user
        try:
            user = User.objects.create_user(username, email, password)
            user.save()

        except IntegrityError:
            return render(request, "network/register.html", {
                "Message": "Username already taken."
            })


        login(request, user)
        return HttpResponseRedirect(reverse("network:index"))
    else:

        return render(request, "network/register.html" )

"""__________________________________________________________________________________________________"""

@login_required
@csrf_exempt
def profile(request,username):
    if request.user.is_authenticated:
        profile= []
        UserPosts = []
        TFollowers = 0
        TFollowing = 0

        searchuser = username
        userid = User.objects.filter(username=searchuser).values('id')
        print("inside profile")
        for u in userid:
            User_id = int(u['id'])
        print(userid, User_id )
        profile = Profile.objects.filter(User=User_id )
        UserPosts = Posts.objects.filter(User=User_id).order_by('-Date')

        for FS in profile:
            TFollowers = FS.Follower.all().count() #total followers
            UFollowers = FS.Follower.all() #followers names

        for FG in profile:
            TFollowing = FG.Following.all().count() #total following
            UFollowing = FG.Following.all() #following names

        if request.user.id == User_id:
            ShowFollowornot = "no"
        else:
            ShowFollowornot = "yes"


        if request.user in UFollowers:
           btnfollow = "Unfollow"
        else:
            btnfollow = "Follow"

        paginator = Paginator(UserPosts, 10)
        page_number = request.GET.get('page')
        page_itens = paginator.get_page(page_number)

        #print("PROFILE PAGE")
        #print(paginator.count , paginator.num_pages )

        context={
            "User":searchuser,
            "Profiles":profile,
            "TotalFollowers":TFollowers,
            "TotalFollowing":TFollowing,
            "ShowFollowornot" :ShowFollowornot,
            "btnfollow" : btnfollow,
            "UserFollowers":UFollowers,
            "Userfollowing":UFollowing ,
            "page_obj": page_itens,
            "UserEdit" : request.user.username,

        }
        return render(request, "network/profile.html", context)
    else:
        context={
            "Message": "Please Login or join our Network",
        }
        return render(request, "network/login.html", context)


@login_required
def post_view(request,username):

    if request.method == "POST":
        PV = NewPostForm(request.POST)
        if PV.is_valid():
            PV_user=request.user
            PV_post=PV.cleaned_data["NewPost"]
            try:
                NewPost = Posts(User=PV_user  , Post=PV_post)
                NewPost.save()

                paginator = Paginator(allposts(), 10)
                page_number = request.GET.get('page')
                page_itens = paginator.get_page(page_number)
                #print("ALL POSTS PAGE")
                #print(paginator.count , paginator.num_pages )

                context={
                    "NewPostForm":NewPostForm(),
                    "page_obj": page_itens,
                }
                return render(request, "network/index.html", context)
            except IntegrityError as e:
                return HttpResponse( "ERROR trying to save New Post." + e )
    else:
            context={
               "NewPostForm":NewPostForm(),
               "page_obj": allposts(),
               "Username":username,
            }
            return render(request, "network/index.html", context)





@login_required
def following_view(request):
    FPL = []
    profile= []
    following = []
    posts = []
    postchoose = []

    if request.user.is_authenticated:
          posts = Posts.objects.all().order_by('-Date')
          user = request.user.id
          username = request.user.username
          seguindo = Profile.objects.filter(Follower=user)
          print(user, seguindo )

          for row in posts:
              for s in seguindo:
                  if row.User == s.User:
                      #r.append(s.Avatar) como juntar a foto na query?
                      FPL.append(row)

          paginator = Paginator(FPL, 10)
          page_number = request.GET.get('page')
          page_itens = paginator.get_page(page_number)
    else:
        context={
            "Message": "Please Login or join our Network",
        }
        return render(request, "network/login.html", context)


    context = {
         "page_obj" : page_itens,
         "NewPostForm":NewPostForm(),
    }

    return render(request, "network/following.html", context)




def allposts():
    with connection.cursor() as cursor:
        cursor.execute(f"""
            SELECT u.username, pr.Avatar,po.id, po.Post, po.Date, po.Likes, po.Unlikes
            FROM network_user u, network_profile pr, network_posts po
            WHERE pr.User_id = po.User_id AND po.User_id = u.id
            ORDER BY po.Date DESC""")
        results = dictfetchall(cursor)
    return results


def dictfetchall(cursor):
    "Return all rows from a cursor as a dict"
    columns = [col[0] for col in cursor.description]
    return [
        dict(zip(columns, row))
        for row in cursor.fetchall()
    ]

"""
___________________________________________________  APIs_______________________________________________________
"""


#testing
@login_required
@csrf_exempt
def followme(request):
    if request.method == "PUT":
        data = json.loads(request.body)

        ProfToChange1 = Profile.objects.get(User=data['id']) #profile id
        ProfToChange2 = Profile.objects.get(User=data['follower'])

        try:
            if data['fornot'] == "Follow": #Follow our unfollow
               ProfToChange1.Follower.add(data['follower'])  #Follower id add
               ProfToChange1.save()
               ProfToChange2.Following.add(data['id']) #Following id add
               ProfToChange2.save()

            if data['fornot'] == "Unfollow":
                ProfToChange1.Follower.remove(data['follower'])
                ProfToChange1.save()
                ProfToChange1.Follower.remove(data['id'])
                ProfToChange2.save()


            return JsonResponse({"Message": "Followers successfully changed."}, status=201)
        except:
            return JsonResponse({"error": "Something Wrong trying to save changes." }, status=400)

    return HttpResponse(status=204)

@login_required
@csrf_exempt
def editpost_view(request):
    if request.method == "PUT":
        data = json.loads(request.body)
        id = int(data['postid'])
        newpost = data['newtext']
        Posttochange = Posts.objects.get(id=id)
        try:
            Posttochange.Post= newpost
            Posttochange.save()
            return JsonResponse({"Message": "Post successfully changed "}, status=201)
        except Exception as e:
            return JsonResponse({"error": f"{e} "  })
    else:

network/templates/network/following.html
{% extends "network/layout.html" %}
{% load static %}
{% block body %}
  <h1>Following </h1>
  <hr>
  <h1>{{Message}}</h1>

{% if page_obj|length > 0 %}
        {% for Post in page_obj %}
            <div class="container" style="width:90%; position:relative; top:100px;background-image: linear-gradient(to top left, #000033, gray,	 #000033 );">
                <div class="row"  width="1700px">
                    <div class="col-lg-2">
                        <p><a href= "{% url 'network:profile' Post.User %}"  >  {{Post.User |title}} </a>
                        <img src="/media/{{Post.Avatar}} "  class="img-responsive" style="width: 80px;"   />
                    </div>

                    <div class="col-lg-4">
                         <p> {{Post.Post}} </p>
                    </div>
                    <div class="col-lg-1" style="text-align: center;">
                         {%if Post.Likes == None%}
                             <p> 0 <i class="fas fa-thumbs-up"></i></p>
                         {% else %}
                              <p> {{ Post.Likes }}  <i class="fas fa-thumbs-up"></i></p>
                         {% endif %}
                    </div>
                    <div class="col-lg-1" style="text-align: center;">
                         {%if Post.Unlikes  == None%}
                              <p> 0  <i class="fas fa-thumbs-down"></i></p>
                         {% else %}
                              <p> {{ Post.Unlikes }}  <i class="fas fa-thumbs-down"></i></p>
                          {% endif %}
                    </div>
                    <div class="col-lg-3">
                       <p> {{Post.Date}} </p>
                    </div>
                    <div class="col-lg-1">

                       <input type="hidden" id="post_id"  value ={{Post.id}} >
                       <input type="hidden" id="pagename"  value ="following" >
                       <p> <button class="btn btn-primary" id="likes-{{Post.id}}" onclick="likepost({{Post.id}})">
                            <i class="far fa-thumbs-up"></i>
                           </button></p>
                       <p> <button class="btn btn-primary" id="unlikes-{{Post.id}}" onclick="unlikepost({{Post.id}})">
                            <i class="far fa-thumbs-down"></i>
                           </button></p>
                    </div>

                </div>
            </div>
            <br>
        {% endfor %}
        <br>
        <hr>
        <form>
           <div class="container" >
              <ul class="pagination justify-content-center"  >
                  {% if page_obj.has_previous %}
                            <li class="page-item"><a href="?page=1" class="page-link" style="background-color:#e6ffff;">&laquo; First</a></li>
                            <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link" style="background-color:#e6ffff;">Previous</a></li>
                  {% else %}
                        <li class="page-item disabled"><a class="page-link" style="background-color:#e6ffff;">&laquo; First</a></li>
                        <li class="page-item disabled"><a class="page-link" style="background-color:#e6ffff;">Previous</a></li>
                  {% endif %}
                  {% if page_obj.number %}
                        <li class="page-item"><a class="page-link" style="background-color:#e6ffff;">{{ page_obj.number }}</a></li>
                  {% else %}
                        <li class="page-item"><a class="page-link" style="background-color:#e6ffff;">0</a></li>
                  {% endif %}
                  {% if page_obj.has_next %}
                        <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link" style="background-color:#e6ffff;">Next</a></li>
                        <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link" style="background-color:#e6ffff;">Last &raquo;</a></li>
                  {% else %}
                        <li class="page-item disabled"><a class="page-link" style="background-color:#e6ffff;">Next</a></li>
                        <li class="page-item disabled"><a class="page-link" style="background-color:#e6ffff;">Last &raquo;</a></li>
                  {% endif %}
            </ul>
          </div>
        </form>
    {% endif %}
    {% block script %}
          <script type="text/javascript" src="{% static 'network/likes.js'  %}" ></script>
    {% endblock %}


    {% endblock %}

network/templates/network/index.html
{% extends "network/layout.html" %}
{% load static %}


{% block body %}
  <h1>All Posts</h1>
  <hr>
  <h1>{{Message}}</h1>


  <div class="container" >
      <form action="{% url 'network:post' request.user %}" method="post" style="border: 1px solid #e6ffff ;">
          {% csrf_token %}
          <p style="text-align:center;">
            {{request.user |title}}
            {{ NewPostForm }}
            <br>
            <button class="btn btn-primary" type="Submit" id="newpost" name="newpost">Post</button></p>
      </form>
  </div>



  {% if page_obj|length > 0 %}
      {% for Post in page_obj %}
          <div class="container" style="width:90%; position:relative; top:100px;background-image: linear-gradient(to top left, #000033, gray,	 #000033 );">
              <div class="row"  width="1700px">
                  <div class="col-lg-2">
                      <p><a href="{% url 'network:profile' Post.username %}" >  {{Post.username |title}} </a> </p>
                      <input type="hidden" id="post_id"  value = {{Post.id}} >
                      <input type="hidden" id="pagename"  value ="post" >
                      {% if UserEdit == Post.username %}
                          <p> <button class="btn btn-primary" id="edit-{{Post.id}}" onclick="editpost({{Post.id}})">
                                 Edit Post
                               </button></p>
                      {%endif%}
                  </div>
                  <div class="col-lg-1">
                          <img src="/media/{{Post.Avatar}} "  class="img-responsive" style="width: 80px;"   />
                  </div>
                  <div class="col-lg-3">
                      <div id="divpost-{{Post.id}}"  >
                           <p id={{Post.id}}> {{Post.Post}} </p>
                      </div>
                  </div>
                  <div class="col-lg-1" style="text-align: center;">
                           {%if Post.Likes == None%}
                             <p> 0 <i class="fas fa-thumbs-up"></i></p>
                           {% else %}
                              <p> {{ Post.Likes }}  <i class="fas fa-thumbs-up"></i></p>
                           {% endif %}
                  </div>
                  <div class="col-lg-1" style="text-align: center;">
                           {%if Post.Unlikes  == None%}
                                <p> 0  <i class="fas fa-thumbs-down"></i></p>
                            {% else %}
                                <p> {{ Post.Unlikes }}  <i class="fas fa-thumbs-down"></i></p>
                            {% endif %}

                      </div>
                      <div class="col-lg-3">
                         <p> {{Post.Date}} </p>
                      </div>
                      <div class="col-lg-1">
                          <p> <button class="btn btn-primary" id="likes-{{Post.id}}" onclick="likepost({{Post.id}})">
                               <i class="far fa-thumbs-up"></i>
                              </button></p>
                          <p> <button class="btn btn-primary" id="unlikes-{{Post.id}}" onclick="unlikepost({{Post.id}})">
                               <i class="far fa-thumbs-down"></i>
                              </button></p>

                      </div>
                  </div>
          </div>
          <hr>


      {% endfor %}
      <br>
      <hr>
      <form>
         <div class="container" >
            <ul class="pagination justify-content-center"  >
                {% if page_obj.has_previous %}
                          <li class="page-item"><a href="?page=1" class="page-link" style="background-color:#e6ffff;">&laquo; First</a></li>
                          <li class="page-item"><a href="?page={{ page_obj.previous_page_number }}" class="page-link" style="background-color:#e6ffff;">Previous</a></li>
                {% else %}
                      <li class="page-item disabled"><a class="page-link" style="background-color:#e6ffff;">&laquo; First</a></li>
                      <li class="page-item disabled"><a class="page-link" style="background-color:#e6ffff;">Previous</a></li>
                {% endif %}
                {% if page_obj.number %}
                      <li class="page-item"><a class="page-link" style="background-color:#e6ffff;">{{ page_obj.number }}</a></li>
                {% else %}
                      <li class="page-item"><a class="page-link" style="background-color:#e6ffff;">0</a></li>
                {% endif %}
                {% if page_obj.has_next %}
                      <li class="page-item"><a href="?page={{ page_obj.next_page_number }}" class="page-link" style="background-color:#e6ffff;">Next</a></li>
                      <li class="page-item"><a href="?page={{ page_obj.paginator.num_pages }}" class="page-link" style="background-color:#e6ffff;">Last &raquo;</a></li>
                {% else %}
                      <li class="page-item disabled"><a class="page-link" style="background-color:#e6ffff;">Next</a></li>
                      <li class="page-item disabled"><a class="page-link" style="background-color:#e6ffff;">Last &raquo;</a></li>
                {% endif %}
          </ul>
        </div>
      </form>
  {% endif %}

  {% block script %}
      <script type="text/javascript" src="{% static 'network/editpost.js' %}" ></script>
      <script type="text/javascript" src="{% static 'network/likes.js' %}" ></script>
  {% endblock %}

  {% endblock %}

network/templates/network/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Social Network{% endblock %}</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
        <link href="{% static 'network/styles.css' %}" rel="stylesheet">
        <link rel="icon"  type="image/png"  href="{% static 'images/Network.png' %}">
        <script src="https://kit.fontawesome.com/a076d05399.js"></script>
    </head>
    <body>

        <nav class="navbar navbar-expand-lg navbar-light bg-light" >
            <a class="navbar-brand" href="#">Network</a>

            <div style="color : #000033;">
              <ul class="navbar-nav mr-auto">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:profile' user.username  %}"><strong>{{ user.username |title}}</strong></a>
                    </li>


                {% endif %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'network:index' %}">All Posts</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:following' %}">Following</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:logout' %}">Log Out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:login' %}">Log In</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'network:register' %}">Register</a>
                    </li>
                {% endif %}
              </ul>
            </div>
          </nav>

        <div class="body">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

network/templates/network/login.html
{% extends "network/layout.html" %}

{% block body %}
    <br>
    <h2 style="text-align: center;">Login</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:login' %}" method="post" style="text-align: center;">
        {% csrf_token %}
        <div class="form-group" style="margin:auto; width: 50%;">
            <input autofocus class="form-control" type="text" name="username" placeholder="Username">
        </div>
        <br>
        <div class="form-group" style="margin:auto; width: 50%;">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <br>
        <div class="form-group" style="align-items: center;" >
             <input class="btn btn-primary" type="submit" value="Login">
             Don't have an account? <a href="{% url 'network:register' %}">Register here.</a>
        </div>
    </form>



{% endblock %}

network/templates/network/register.html
{% extends "network/layout.html" %}

{% block body %}

    <h2 style="text-align: center;">Register</h2>

    {% if message %}
        <div>{{ message }}</div>
    {% endif %}

    <form action="{% url 'network:register' %}" method="post" style="text-align: center;">
        {% csrf_token %}
        <div class="form-group" style="margin:auto; width: 50%;">
            <input class="form-control" autofocus type="text" name="username" placeholder="Username">
        </div>
        <br>
        <div class="form-group" style="margin:auto; width: 50%;">
            <input class="form-control" type="email" name="email" placeholder="Email Address">
        </div>
          <br>
        <div class="form-group" style="margin:auto; width: 50%;">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
          <br>
        <div class="form-group" style="margin:auto; width: 50%;">
            <input class="form-control" type="password" name="confirmation" placeholder="Confirm Password">
        </div>
          <br>

        <br>

        <div class="form-group" style="text-align: center;">
             <input class="btn btn-primary" type="submit" value="Register">
             Already have an account? <a href="{% url 'network:login' %}">Log In here.</a>
        </div>
    </form>



{% endblock %}